<a href="https://colab.research.google.com/github/SamShinwari/Python-Programming/blob/main/Matrix_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **📘 Week 1 — Jupyter Notebook Exercise**
## Linear Algebra for Machine Learning
## Topic: Scalars, Vectors, Matrices, and Tensors

#🧠 Exercise Objectives

In this notebook, students will learn how to:



*   Create scalars, vectors, matrices, and tensors
*   Understand dimensions and shapes
*   Represent ML datasets using matrices
*   Perform simple vector and matrix operations
*   Connect Linear Algebra concepts to Machine Learning

# 📦 Step 1 — Import NumPy

In [ ]:
import numpy as np

# **1️⃣ Scalars**

## A scalar is a single numerical value.

# **✅ Example**

In [ ]:
scalar = np.array(10)

print("Scalar:", scalar)
print("Dimensions:", scalar.ndim)
print("Shape:", scalar.shape)

Scalar: 10
Dimensions: 0
Shape: ()


**#🧪 Exercise 1**

Create a scalar representing:

*  learning rate = 0.01

Print:

*   **value**
*   **dimensions**
*    **shape**

In [ ]:
learning_rate = np.array(0.01)

print("Learning Rate:", learning_rate)
print("Dimensions:", learning_rate.ndim)
print("Shape:", learning_rate.shape)

Learning Rate: 0.01
Dimensions: 0
Shape: ()


# **2️⃣ Vectors**

A vector is an ordered list of numbers.

✅ Example

In [ ]:
vector = np.array([2, 4, 6])

print("Vector:", vector)
print("Dimensions:", vector.ndim)
print("Shape:", vector.shape)

Vector: [2 4 6]
Dimensions: 1
Shape: (3,)


# **📌 Feature Vector Example**

One student's data:

*  Age = 21
*  Study hours = 5
*  GPA = 3.7

In [ ]:
student = np.array([21,5,3.7])
print("Student:", student)
print("Dimensions:", student.ndim)
print("Shape:", student.shape)

Student: [21.   5.   3.7]
Dimensions: 1
Shape: (3,)


# **🧪 Exercise 2**

Create a vector representing:

temperature readings = [30, 32, 35, 31]

Print:

* vector
* shape
* dimensions

In [ ]:
tempreadings = np.array([30, 32, 35, 31])

print("Temperature Readings:", tempreadings)
print("Dimensions:", tempreadings.ndim)
print("Shape:", tempreadings.shape)

Temperature Readings: [30 32 35 31]
Dimensions: 1
Shape: (4,)


# 3️⃣ Matrix

A matrix contains rows and columns.

## ✅ Example

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A)
print("Shape:", A.shape)
print("Dimensions:", A.ndim)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2


## 📌 Machine Learning Dataset as Matrix

In [ ]:
X = np.array([
    [21, 5, 3.7],
    [22, 6, 3.5],
    [20, 4, 3.9]
])

print(X)

[[21.   5.   3.7]
 [22.   6.   3.5]
 [20.   4.   3.9]]


## 📊 Understanding Shape

In [ ]:
print("Rows (samples):", X.shape[0])
print("Columns (features):", X.shape[1])

Rows (samples): 3
Columns (features): 3


# 🧪 Exercise 3: Matrix Creation and Properties

## Objective
Create a matrix using student data and print its:

- Matrix values  
- Shape  
- Dimensions  

### Given Data

| Age | Hours | GPA |
|------|------|-----|
| 19 | 3 | 3.2 |
| 20 | 5 | 3.8 |
| 21 | 4 | 3.6 |
| 22 | 6 | 3.9 |

### Tasks
1. Create a matrix using NumPy.  
2. Print the matrix.  
3. Print the shape of the matrix.  
4. Print the dimensions of the matrix.  



In [ ]:
student = np.array([[19,20,21,22],[3,4,5,6],[3.2,3.8,3.6,3.9]])
print("\nStudent Dataset:")
print(student)

print("Dimensions:", student.ndim)
print("Shape:", student.shape)



Student Dataset:
[[19.  20.  21.  22. ]
 [ 3.   4.   5.   6. ]
 [ 3.2  3.8  3.6  3.9]]
Dimensions: 2
Shape: (3, 4)
