<a href="https://colab.research.google.com/github/SamShinwari/Python-Programming/blob/main/NumpyOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **🐍 Week 1 Implementation in Python (NumPy)**

1️⃣ Scalar (0D)

    A scalar is just a single number.





In [ ]:
import numpy as np

# Scalar
a = np.array(5)

print("Scalar:", a)
print("Type:", type(a))
print("Dimension:", a.ndim)

Scalar: 5
Type: <class 'numpy.ndarray'>
Dimension: 0



# **2️⃣ Vector (1D Array)**
A vector is a list of numbers (features).

In [ ]:
# Vector
v = np.array([2, 4, 6])

print("Vector:", v)
print("Shape:", v.shape)
print("Dimension:", v.ndim)

Vector: [2 4 6]
Shape: (3,)
Dimension: 1


# **🎯 Feature Vector Example (Student Data)**

In [ ]:
student = np.array([21, 5, 3.7])  # age, study hours, GPA

print("Student Feature Vector:", student)

Student Feature Vector: [21.   5.   3.7]


In [ ]:
# Matrix (dataset)
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matrix:\n", A)
print("Shape:", A.shape)
print("Dimension:", A.ndim)

Matrix:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimension: 2


# **🎯 ML Dataset Example (Design Matrix)**

In [ ]:
X = np.array([
    [21, 5, 3.7],
    [22, 6, 3.5],
    [20, 4, 3.9]
])

print("Design Matrix:\n", X)
print("Shape:", X.shape)   # (samples, features)

Design Matrix:
 [[21.   5.   3.7]
 [22.   6.   3.5]
 [20.   4.   3.9]]
Shape: (3, 3)


# ***# 4️⃣ Tensor (3D Array)***

A tensor is a multi-dimensional structure.

🎯 Example: Batch of Images

In [ ]:
# Tensor (3 images, 2x2 pixels, 3 RGB channels)
tensor = np.array([
    [
        [[255, 0, 0], [0, 255, 0]],
        [[0, 0, 255], [255, 255, 0]]
    ],
    [
        [[10, 20, 30], [40, 50, 60]],
        [[70, 80, 90], [100, 110, 120]]
    ],
    [
        [[1, 2, 3], [4, 5, 6]],
        [[7, 8, 9], [10, 11, 12]]
    ]
])

print("Tensor shape:", tensor.shape)
print("Dimension:", tensor.ndim)

Tensor shape: (3, 2, 2, 3)
Dimension: 4


# 📊 Real ML Connection Example
Dataset → Matrix

In [ ]:
X = np.array([
    [21, 5, 3.7],
    [22, 6, 3.5],
    [20, 4, 3.9]
])

In [ ]:
weights = np.array([0.3, 0.5, 0.2])

In [ ]:
predictions = np.dot(X, weights)

print("Predictions:", predictions)

Predictions: [ 9.54 10.3   8.78]


# **Tensor Explanation in Deep Learning Style**

In [ ]:
# Batch of 2 grayscale images (3x3)
images = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]
])

print(images.shape)   # (2, 3, 3)
print(images.ndim)    # 3D tensor

(2, 3, 3)
3


# **📌 Summary in Code Form**

In [ ]:
scalar = np.array(10)              # 0D
vector = np.array([1, 2, 3])       # 1D
matrix = np.array([[1, 2], [3, 4]])# 2D
tensor = np.random.rand(2, 3, 3)   # 3D

In [ ]:
print("Scalar: ",scalar)
print("Vector: ",vector)
print("Matrix: ",matrix)
print("Tensor: ",tensor)

Scalar:  10
Vector:  [1 2 3]
Matrix:  [[1 2]
 [3 4]]
Tensor:  [[[0.50225361 0.01471539 0.39153567]
  [0.17100076 0.0862973  0.56196623]
  [0.32095998 0.15229878 0.11694252]]

 [[0.99291585 0.07680081 0.82921614]
  [0.86417269 0.75402759 0.74933493]
  [0.97996717 0.56358155 0.91307442]]]
